
    <style>
        .mymy-container {
            width: 100%;
            height: 400px;
            position: relative;
            overflow-y: scroll;

        }
       .mymy-scroll {
           position: relative;
           width: 100%;
           height: 500px;

        }
    </style>
    <div class="mt-3">
        <div id="container_table" class="mymy-container" >
            <div id="test_table" class="mymy-scroll"></div>
        </div>
    </div>

